# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40d36715fb278ab78e862db6124ab96b15f042eef519918b1e4f0e7264937fd2da860bc12a0a4636cf860598fff60b50f68be2485322ddfc96030acd9c94e6cb

test:
  secret_key_base: 7d8f2932956576eee4efb6b9336877c91e573d2e7ec8e1d9d341373a5e6ee41983044e18c6201e4afa7931a9eea3f90485735da23375fdb411ee35a675f19d52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
